project:
  type: website
  output-dir: docs

website:
  title: "IceCube Reykjavík"
  description: "Magic: The Gathering Cube Draft Event in Iceland"
  site-url: "https://rvkicecube.iss"
  
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: events.qmd
        text: Events
      - href: decklists.qmd
        text: Decklists
      - href: contact.qmd
        text: Contact
    
    right:
      - icon: github
        href: https://github.com/rvkicecube/rvkicecube.github.io
        aria-label: GitHub

  page-footer:
    left: "© 2024 IceCube Reykjavík"
    right: 
      - icon: github
        href: https://github.com/rvkicecube/rvkicecube.github.io
        aria-label: GitHub

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme.scss]
    css: styles.css
    toc: true
    toc-location: right
    code-fold: true
    html-math-method: katex

editor: source
engine: knitr
